// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $api_profile from "./routes/api/profile.ts";
import * as $api_question from "./routes/api/question.ts";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $auth_logged_out from "./routes/auth/logged-out.tsx";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_logout from "./routes/auth/logout.tsx";
import * as $debug from "./routes/debug.tsx";
import * as $emt_practice_index from "./routes/emt/practice/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $leaderboard from "./routes/leaderboard.tsx";
import * as $profile from "./routes/profile.tsx";
import * as $user_user_id_ from "./routes/user/[user_id].tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LoginIsland from "./islands/LoginIsland.tsx";
import * as $NavAvatar from "./islands/NavAvatar.tsx";
import * as $Profile from "./islands/Profile.tsx";
import * as $Question from "./islands/Question.tsx";
import * as $ThemeController from "./islands/ThemeController.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/api/profile.ts": $api_profile,
    "./routes/api/question.ts": $api_question,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/auth/logged-out.tsx": $auth_logged_out,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/logout.tsx": $auth_logout,
    "./routes/debug.tsx": $debug,
    "./routes/emt/practice/index.tsx": $emt_practice_index,
    "./routes/index.tsx": $index,
    "./routes/leaderboard.tsx": $leaderboard,
    "./routes/profile.tsx": $profile,
    "./routes/user/[user_id].tsx": $user_user_id_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/LoginIsland.tsx": $LoginIsland,
    "./islands/NavAvatar.tsx": $NavAvatar,
    "./islands/Profile.tsx": $Profile,
    "./islands/Question.tsx": $Question,
    "./islands/ThemeController.tsx": $ThemeController,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
