// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_debug from "./routes/admin/debug.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_product_manager from "./routes/admin/product-manager.tsx";
import * as $admin_product_manager_product_id_ from "./routes/admin/product-manager/product/[id].tsx";
import * as $admin_question_generator from "./routes/admin/question-generator.tsx";
import * as $admin_question_reports from "./routes/admin/question-reports.tsx";
import * as $api_admin_middleware from "./routes/api/admin/_middleware.ts";
import * as $api_admin_book_content from "./routes/api/admin/book-content.ts";
import * as $api_admin_chapter_content from "./routes/api/admin/chapter-content.ts";
import * as $api_admin_chapters from "./routes/api/admin/chapters.ts";
import * as $api_admin_product from "./routes/api/admin/product.ts";
import * as $api_admin_product_id_index from "./routes/api/admin/product/[id]/index.ts";
import * as $api_admin_product_id_toggle_active from "./routes/api/admin/product/[id]/toggle-active.ts";
import * as $api_admin_product_id_variant_variant_id_ from "./routes/api/admin/product/[id]/variant/[variant_id].ts";
import * as $api_admin_product_id_variant_variant_id_create_stripe_product from "./routes/api/admin/product/[id]/variant/[variant_id]/create-stripe-product.ts";
import * as $api_admin_product_id_variant_variant_id_update_stripe_price from "./routes/api/admin/product/[id]/variant/[variant_id]/update-stripe-price.ts";
import * as $api_admin_product_id_variants from "./routes/api/admin/product/[id]/variants.ts";
import * as $api_admin_question from "./routes/api/admin/question.ts";
import * as $api_checkout from "./routes/api/checkout.ts";
import * as $api_preferences from "./routes/api/preferences.ts";
import * as $api_printful_webhook from "./routes/api/printful_webhook.ts";
import * as $api_profile from "./routes/api/profile.ts";
import * as $api_question from "./routes/api/question.ts";
import * as $api_question_reports from "./routes/api/question/reports.ts";
import * as $api_stripe_webhook from "./routes/api/stripe_webhook.ts";
import * as $api_support from "./routes/api/support.ts";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $auth_logged_out from "./routes/auth/logged-out.tsx";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_logout from "./routes/auth/logout.tsx";
import * as $cart from "./routes/cart.tsx";
import * as $checkout_success from "./routes/checkout/success.tsx";
import * as $emt_practice_index from "./routes/emt/practice/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $leaderboard from "./routes/leaderboard.tsx";
import * as $profile from "./routes/profile.tsx";
import * as $robots_txt from "./routes/robots.txt.ts";
import * as $shop from "./routes/shop.tsx";
import * as $shop_id_ from "./routes/shop/[id].tsx";
import * as $support from "./routes/support.tsx";
import * as $user_user_id_ from "./routes/user/[user_id].tsx";
import * as $AdminQuestionGenerator from "./islands/AdminQuestionGenerator.tsx";
import * as $CartClearer from "./islands/CartClearer.tsx";
import * as $CartIcon from "./islands/CartIcon.tsx";
import * as $CartPageIsland from "./islands/CartPageIsland.tsx";
import * as $NavAvatar from "./islands/NavAvatar.tsx";
import * as $PWAInstallPrompt from "./islands/PWAInstallPrompt.tsx";
import * as $ProductCard from "./islands/ProductCard.tsx";
import * as $ProductDetails from "./islands/ProductDetails.tsx";
import * as $Profile from "./islands/Profile.tsx";
import * as $Question from "./islands/Question.tsx";
import * as $StreakIndicator from "./islands/StreakIndicator.tsx";
import * as $ThemeController from "./islands/ThemeController.tsx";
import * as $admin_ProductDetail from "./islands/admin/ProductDetail.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/debug.tsx": $admin_debug,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/product-manager.tsx": $admin_product_manager,
    "./routes/admin/product-manager/product/[id].tsx":
      $admin_product_manager_product_id_,
    "./routes/admin/question-generator.tsx": $admin_question_generator,
    "./routes/admin/question-reports.tsx": $admin_question_reports,
    "./routes/api/admin/_middleware.ts": $api_admin_middleware,
    "./routes/api/admin/book-content.ts": $api_admin_book_content,
    "./routes/api/admin/chapter-content.ts": $api_admin_chapter_content,
    "./routes/api/admin/chapters.ts": $api_admin_chapters,
    "./routes/api/admin/product.ts": $api_admin_product,
    "./routes/api/admin/product/[id]/index.ts": $api_admin_product_id_index,
    "./routes/api/admin/product/[id]/toggle-active.ts":
      $api_admin_product_id_toggle_active,
    "./routes/api/admin/product/[id]/variant/[variant_id].ts":
      $api_admin_product_id_variant_variant_id_,
    "./routes/api/admin/product/[id]/variant/[variant_id]/create-stripe-product.ts":
      $api_admin_product_id_variant_variant_id_create_stripe_product,
    "./routes/api/admin/product/[id]/variant/[variant_id]/update-stripe-price.ts":
      $api_admin_product_id_variant_variant_id_update_stripe_price,
    "./routes/api/admin/product/[id]/variants.ts":
      $api_admin_product_id_variants,
    "./routes/api/admin/question.ts": $api_admin_question,
    "./routes/api/checkout.ts": $api_checkout,
    "./routes/api/preferences.ts": $api_preferences,
    "./routes/api/printful_webhook.ts": $api_printful_webhook,
    "./routes/api/profile.ts": $api_profile,
    "./routes/api/question.ts": $api_question,
    "./routes/api/question/reports.ts": $api_question_reports,
    "./routes/api/stripe_webhook.ts": $api_stripe_webhook,
    "./routes/api/support.ts": $api_support,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/auth/logged-out.tsx": $auth_logged_out,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/logout.tsx": $auth_logout,
    "./routes/cart.tsx": $cart,
    "./routes/checkout/success.tsx": $checkout_success,
    "./routes/emt/practice/index.tsx": $emt_practice_index,
    "./routes/index.tsx": $index,
    "./routes/leaderboard.tsx": $leaderboard,
    "./routes/profile.tsx": $profile,
    "./routes/robots.txt.ts": $robots_txt,
    "./routes/shop.tsx": $shop,
    "./routes/shop/[id].tsx": $shop_id_,
    "./routes/support.tsx": $support,
    "./routes/user/[user_id].tsx": $user_user_id_,
  },
  islands: {
    "./islands/AdminQuestionGenerator.tsx": $AdminQuestionGenerator,
    "./islands/CartClearer.tsx": $CartClearer,
    "./islands/CartIcon.tsx": $CartIcon,
    "./islands/CartPageIsland.tsx": $CartPageIsland,
    "./islands/NavAvatar.tsx": $NavAvatar,
    "./islands/PWAInstallPrompt.tsx": $PWAInstallPrompt,
    "./islands/ProductCard.tsx": $ProductCard,
    "./islands/ProductDetails.tsx": $ProductDetails,
    "./islands/Profile.tsx": $Profile,
    "./islands/Question.tsx": $Question,
    "./islands/StreakIndicator.tsx": $StreakIndicator,
    "./islands/ThemeController.tsx": $ThemeController,
    "./islands/admin/ProductDetail.tsx": $admin_ProductDetail,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
